---
- name: check if firewalld package in installed
  shell: yum list installed firewalld
  args:
    warn: no
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
  when: ansible_os_family == "RedHat" and firewall_disable_firewalld

- name: disable firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat" and firewall_disable_firewalld and firewalld_installed.stdout != ""


