---
- include: disable-other-firewall.yml

- name: installed iptables
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables
    - iptables-services

- name: start iptables
  service:
    name: iptables
    state: started
    enabled: yes
