---
- name: create mysql user 
  user: name={{ mysql_user }} state=present createhome=no shell=/sbin/nologin
  when: ansible_os_family == "RedHat"

- name: copy install mysql script
  template:
    src: install_mysql.sh
    dest: /tmp/
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == "RedHat"

- name: copy configure file
  template:
    src: my.cnf
    dest: /tmp/
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "RedHat"

- name: copy mysql security script 
  template:
    src: mysql_security.sh
    dest: /tmp/
    owner: root
    group: root
    mode: 0755
  when: ansible_os_family == "RedHad"

